name: Zig CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Book test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: Run tests
        run: ./.ci-test.sh